// Generated by CoffeeScript 1.8.0
(function() {
  define(['text!templates/ui.html', 'css!styles/ui'], function(tmplUI) {
    return this.UI = (function() {
      function UI() {
        $.templates({
          tmplUI: tmplUI
        });
        $.templates.tmplUI.link('body', this);
      }

      return UI;

    })();
  });

}).call(this);
