// Generated by CoffeeScript 1.8.0
(function() {
  var HTTPServerRouter, URL;

  URL = require("url");

  HTTPServerRouter = (function() {
    function HTTPServerRouter() {}

    HTTPServerRouter.prototype.route = function(request, response) {
      var Handler, data, exception, handler, path, pathParts;
      request.setEncoding("utf8");
      data = URL.parse(request.url, true);
      path = data.pathname;
      pathParts = path.split("/");
      path = pathParts.map(function(part) {
        if (part.length > 0) {
          return part[0].toUpperCase() + part.slice(1);
        } else {
          return "";
        }
      }).join("").slice(1);
      if (/\./.test(pathParts[pathParts.length - 1])) {
        Handler = require("../HTTPHandlers/ResourceHandler");
      } else {
        try {
          Handler = require("../HTTPHandlers/" + path + "Handler");
        } catch (_error) {
          exception = _error;
          Handler = require("../HTTPHandlers/404Handler");
        }
      }
      handler = new Handler(request, response);
      return handler.execute();
    };

    return HTTPServerRouter;

  })();

  module.exports = HTTPServerRouter;

}).call(this);
