// Generated by CoffeeScript 1.8.0
(function() {
  var HTTP, HTTPRouter, HTTPServer;

  HTTP = require("http");

  HTTPRouter = require("./HTTPServerRouter");

  HTTPServer = (function() {
    function HTTPServer() {
      this.router = new HTTPRouter;
    }

    HTTPServer.prototype.run = function(port) {
      var router;
      router = this.router;
      return HTTP.createServer(function(request, response) {
        return router.route(request, response);
      }).listen(port);
    };

    return HTTPServer;

  })();

  module.exports = HTTPServer;

}).call(this);
